### ISSUE TITLE
Loading LLaVA-Next results in an error

### ISSUE THREAD

**Issue by aadarsh-ram** [UW-Madison-Lee-Lab/CoBSAT#1]
I followed the Linux setup instructions for the conda env given in the README, and was able to setup LLaVA successfully. 

But, trying to load LLaVA-Next with the same conda env results in the following error:
```
File "/<prefix>/CoBSAT/models/llava16/llava/__init__.py", line 1, in <module>
from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'models.llava16.llava.model' (/<prefix>/CoBSAT/models/llava16/llava/model/__init__.py)
```

I narrowed it down to the missing function (`get_anyres_image_grid_shape`) in `models/llava16/mm_utils.py`.
Even after adding the function from the [submodule commit](https://github.com/wjkang-furiosa/LLaVA/blob/1d180ae2689b0a990b52affe941cdec234ebdd29/llava/mm_utils.py), there are issues with `transformers` also. I feel there might be some issue with the dependencies for running LLaVA-Next.

Please let me know how to rectify the dependencies, so that LLaVA-Next can be run with the same codebase.

**Comment by yzeng58** [comment]
Thanks so much for your interest in our work and bringing this issue into our attention. 

For LLaVA-NeXT, the llava package version must be newer than 1.2.0. Therefore, you can either clone the original llava environment and then install the latest llava package [here](https://github.com/haotian-liu/LLaVA#upgrade-to-latest-code-base), or follow our updated instruction on the readme file. The updated environment file is provided in `conda_env/` now. 

Feel free to let us know if you have further questions.

**Comment by aadarsh-ram** [comment]
Hey @yzeng58,

There are a couple of issues that I faced while trying to install:
- I think `llava==1.2.2.post1` isn't a pip package, so while running `conda env create -f conda_env/llava16.yml`, it results in an error. It seems to be rectified, if I go to the `models/llava16` folder and install the requirements from there. So, please look into updating the YML file.
- Even after doing this, I have a variety of warnings that come when I instantiate/inference the model. Do these warnings have some effect on the inference?
```
miniconda3/envs/llava16-new/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.post_layernorm.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
```
```
miniconda3/envs/llava16-new/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
/miniconda3/envs/llava16-new/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `None` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
```
(above is a reduced version of the warnings output)
- Also, I noticed a line missing in [your submodule](https://github.com/wjkang-furiosa/LLaVA/blob/1d180ae2689b0a990b52affe941cdec234ebdd29/llava/eval/run_llava.py#L92) for LLaVA-Next. I think `image_sizes=[]` needs to be added before the if block. Please look into that as well.

Thank you for the great work! :)
