### ISSUE TITLE
Script of evaluating  finetune-leaveone_out(eg. color theme)

### ISSUE THREAD

**Issue by ghost** [UW-Madison-Lee-Lab/CoBSAT#2]
Hello, Author, Great Work! Could you give me the script of evaluating  finetune-leaveone_out(eg. color theme)? it should be --data_mode ft_test & --evaluate_theme color ?

**Comment by yzeng58** [comment]
Hi! Thanks for your interest! Yes, you are correct. Here I gave an example for illustration. Evaluating finetune-leaveone_out requires three steps.

* Step 1: Fine-tune the model

```bash
python finetune_icl.py --model qwen --shot 2 --prompt_type default --gen_mode text --ft_mode leave_one_out --eval_task_theme texture
```

* Step 2: Use the fine-tuned model to generate images (or image descriptions)

```bash
python inference_icl.py --model qwen --shot 2 --prompt_type default --gen_mode text --ft_mode leave_one_out --eval_task_theme texture --data_mode ft_test 
```

* Step 3: Evaluate the images (or image descriptions) generated by fine-tuned model

```bash
python evaluation_icl.py --model qwen --shot 2 --eval_mode text --ft_mode leave_one_out --eval_task_theme texture --finetuned_model 1 --data_mode ft_test
```

I also updated the parameters description in the readme. Let me know if you have further questions. Thanks!
